apiVersion: v1
kind: Service
metadata:
  name: transaction-service-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: transaction-service
  type: ClusterIP  