apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-api-gateway
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: cors-plugin, rate-limit
    kubernetes.io/ingress.class: kong
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  number: 8081
          - path: /complain
            pathType: Prefix
            backend:
              service:
                name: complain-service-service
                port:
                  number: 8083
          - path: /transaction
            pathType: Prefix
            backend:
              service:
                name: transaction-service-service
                port:
                  number: 8082
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-server-service
                port:
                  number: 8888
