services:
  postgres:
    image: postgres:15-alpine
    container_name: pg-main
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth-service-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - transaction-microservice-net

  redis:
    image: redis:7-alpine
    container_name: redis-main
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - transaction-microservice-net 

volumes:
  pgdata:
  redisdata:

networks:
  transaction-microservice-net:
    driver: bridge
