apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: 20224886/config-server:latest
        ports:
        - containerPort: 8888
        env:
        - name: GIT_REPO_URI
          valueFrom:
            configMapKeyRef:
              name: config-server-config
              key: GIT_REPO_URI
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: GIT_USERNAME
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: GIT_TOKEN
        - name: CONFIG_SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: CONFIG_SERVER_NAME
        - name: CONFIG_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: CONFIG_SERVER_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION_MS
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: JWT_EXPIRATION_MS
        - name: JWT_REFRESH_EXPIRATION_MS
          valueFrom:
            secretKeyRef:
              name: config-server-secrets
              key: JWT_REFRESH_EXPIRATION_MS
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: config-server-config
              key: SPRING_PROFILES_ACTIVE