services:
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8082:8082"
    env_file:
      - .env.docker
    networks:
      - transaction-microservice-net

networks:
  transaction-microservice-net:
    external: true