services:
  complain-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: complain-service
    ports:
      - "8083:8083"
    env_file:
      - .env.docker
    networks:
      - transaction-microservice-net

networks:
  transaction-microservice-net:
    external: true