apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  type: ClusterIP  # Đây là giá trị mặc định, có thể bỏ qua nếu muốn
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081      # Port mà service sẽ expose trong cluster
      targetPort: 8081 # Port mà container đang lắng nghe
  type: ClusterIP