apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 20224886/auth-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SERVER_PORT
        - name: CONFIG_SERVER_URL
          value: "http://config-server-service:8888"
        - name: CONFIG_SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: CONFIG_SERVER_NAME
        - name: CONFIG_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: CONFIG_SERVER_PASSWORD
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_SECRET
        - name: JWT_EXPIRATION_MS
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_EXPIRATION_MS
        - name: JWT_REFRESH_EXPIRATION_MS
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_REFRESH_EXPIRATION_MS