server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: ${GIT_BRANCH:main}
          clone-on-start: true
          force-pull: true

  security:
    user:
      name: ${CONFIG_SERVER_NAME}
      password: ${CONFIG_SERVER_PASSWORD}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git}

logging:
  level:
    org.springframework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: true
