services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - transaction-microservice-net

networks:
  transaction-microservice-net:
    external: true