name: Build Changed Services and Publish Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  SERVICES: config-server auth-service transaction-service complain-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Tối ưu cho việc detect changes

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect changed services
        id: changed-services
        continue-on-error: true
        run: |
          set -e
          echo "Checking changed files..."
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD || echo "")
          echo "Changed files: $CHANGED_FILES"

          CHANGED_SERVICES=""
          for SERVICE in $SERVICES; do
            for FILE in $CHANGED_FILES; do
              if [[ "$FILE" == backend/$SERVICE/* ]]; then
                CHANGED_SERVICES="$CHANGED_SERVICES $SERVICE"
                break
              fi
            done
          done

          CHANGED_SERVICES=$(echo $CHANGED_SERVICES | tr ' ' '\n' | sort -u | xargs)
          echo "Changed services: $CHANGED_SERVICES"
          echo "services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT

      - name: Build and push changed services
        if: steps.changed-services.outputs.services != ''
        run: |
          set -e
          for SERVICE in ${{ steps.changed-services.outputs.services }}; do
            echo "=== Building $SERVICE ==="
            
            # Step 1: Build JAR
            cd backend/$SERVICE
            echo "Granting execute permission to mvnw"
            chmod +x mvnw  # Fix permission denied error
            
            echo "Building JAR..."
            ./mvnw clean package -DskipTests
            
            # Step 2: Prepare Docker build
            cd ../../
            JAR_FILE=$(ls backend/$SERVICE/target/*.jar | grep -v 'original-' | head -n 1)
            echo "Using JAR file: $JAR_FILE"
            cp "$JAR_FILE" "$SERVICE.jar"

            # Step 3: Build and push Docker image
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "Building Docker image..."
            docker build \
              --build-arg JAR_FILE=$SERVICE.jar \
              -t $DOCKERHUB_USERNAME/$SERVICE:latest \
              -t $DOCKERHUB_USERNAME/$SERVICE:$SHORT_SHA \
              -f backend/docker/Dockerfile .

            echo "Pushing to Docker Hub..."
            docker push $DOCKERHUB_USERNAME/$SERVICE:latest
            docker push $DOCKERHUB_USERNAME/$SERVICE:$SHORT_SHA
            
            # Cleanup
            rm -f "$SERVICE.jar"
            echo "=== Completed $SERVICE ==="
          done

      - name: Verify pushed images
        if: steps.changed-services.outputs.services != ''
        run: |
          for SERVICE in ${{ steps.changed-services.outputs.services }}; do
            echo "Verify $SERVICE:"
            docker pull $DOCKERHUB_USERNAME/$SERVICE:latest
            docker images | grep $SERVICE
          done

      - name: No changes detected
        if: steps.changed-services.outputs.services == ''
        run: echo "✅ No service code changes detected. Skipping build."